layout_spectrum: 0.6947724
color:
  saturation: 0
  brandStrength: 0.1778339
  lightness: 0.796796
  rhythmicContrast: 0.6686341
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
typography_spectrum: 0.648398
name: Juliuszielenieckiphotographer
